/**
 * Risk rule definitions for PR Risk Analyzer
 * Each rule defines: id, name, severity, patterns, description, recommendation
 */

const RISK_RULES = [
  // ── Database & Migrations ───────────────────────────────────────────────
  {
    id: 'DB_MIGRATION_ADD',
    category: 'database',
    severity: 'critical',
    name: 'New Database Migration Detected',
    filePatterns: [
      '**/migrations/**/*.sql',
      '**/migrate*/**/*.sql',
      '**/db/migrate/**',
      '**/db/seeds/**',
      '**/alembic/versions/**',
      '**/flyway/**/*.sql',
      '**/liquibase/**/*.xml',
      '**/*migration*.py',
      '**/migrations/**/*.ts',
      '**/migrations/**/*.js',
      '**/knexfile.js',
      '**/prisma/migrations/**',
      '**/typeorm/migrations/**',
      '**/sequelize-cli/**/migrations/**',
    ],
    description: 'This PR introduces a new database migration. Migrations can cause data loss or schema conflicts in production.',
    recommendation: 'Ensure this migration is reviewed by your DBA. Test against a production-like environment snapshot. Consider backward compatibility.',
    emoji: '🗄️',
  },
  {
    id: 'DB_MIGRATION_MODIFY',
    category: 'database',
    severity: 'critical',
    name: 'Existing Migration Modified',
    filePatterns: [
      '**/migrations/**',
      '**/alembic/versions/**',
      '**/flyway/**/*.sql',
      '**/liquibase/**',
    ],
    description: 'This PR modifies an existing migration. Altering committed migrations can cause irreversible data corruption in environments where the original migration has already run.',
    recommendation: 'Never modify committed migrations. Instead, create a new migration to alter the schema. Rollback and re-apply migration strategy is risky.',
    emoji: '🗄️',
  },
  {
    id: 'DB_MODEL_ADD_COLUMN',
    category: 'database',
    severity: 'high',
    name: 'New Database Column Added',
    contentPatterns: [
      { pattern: /ALTER\s+TABLE.*ADD\s+(?:COLUMN\s+)?/i, flags: '' },
      { pattern: /createTable.*addColumn/i, flags: '' },
      { pattern: /addColumn.*createTable/i, flags: '' },
      { pattern: /field:\s*\{.*type:\s*DataTypes\./i, flags: '' },
      { pattern: /@Column\(\)/i, flags: '' },
    ],
    description: 'This PR adds a new column to an existing database table. Unplanned columns can break applications expecting a specific schema.',
    recommendation: 'Verify the application handles NULL/missing values for this column. Update all related queries and ORM models.',
    emoji: '📊',
  },
  {
    id: 'DB_SEED_DATA',
    category: 'database',
    severity: 'medium',
    name: 'Seed/Test Data Changes',
    filePatterns: [
      '**/seeds/**',
      '**/seeders/**',
      '**/fixtures/**',
      '**/db/seeds/**',
      '**/data/seed*',
      '**/*fixture*',
    ],
    description: 'This PR modifies seed data or test fixtures. Ensure production-equivalent environments are not affected.',
    recommendation: 'Confirm this data is only for development/testing. Review if production seeds are impacted.',
    emoji: '🌱',
  },

  // ── Security ─────────────────────────────────────────────────────────────
  {
    id: 'SECRET_HARDCODED',
    category: 'security',
    severity: 'critical',
    name: 'Potential Hardcoded Secret Detected',
    contentPatterns: [
      { pattern: /(?:api[_-]?key|apikey|api_secret|secret[_-]?key)\s*[:=]\s*['"'][a-zA-Z0-9_\-]{20,}['"]/i, flags: '' },
      { pattern: /password\s*[:=]\s*['"][^'"]{8,}['"]/i, flags: '' },
      { pattern: /(?:aws[_\-]?)?access[_\-]?key[_\-]?id\s*[:=]\s*['"][A-Z0-9]{16,}['"]/i, flags: '' },
      { pattern: /bearer\s+[a-zA-Z0-9_\-\.]{20,}/i, flags: '' },
      { pattern: /-----BEGIN\s+(?:RSA\s+)?PRIVATE\s+KEY-----/i, flags: '' },
      { pattern: /ghp_[a-zA-Z0-9]{36,}/i, flags: '' },
      { pattern: /sk_[a-zA-Z0-9]{32,}/i, flags: '' },
      { pattern: /xox[baprs]-[a-zA-Z0-9]{10,}/i, flags: '' },
      { pattern: /AIza[0-9A-Za-z\\-_]{35}/i, flags: '' },
    ],
    description: 'This PR may contain hardcoded secrets, API keys, or credentials. These should be stored in secrets management.',
    recommendation: 'Remove hardcoded secrets immediately. Use environment variables or GitHub Secrets. Run git-secrets or TruffleHog to scan for leaked credentials.',
    emoji: '🔐',
  },
  {
    id: 'SECURITY_CIPHER_CHANGE',
    category: 'security',
    severity: 'critical',
    name: 'Security/Cipher Configuration Changed',
    filePatterns: [
      '**/ssl/**',
      '**/tls/**',
      '**/certs/**',
      '**/certificate*',
      '**/openssl*',
      '**/nginx*.conf',
      '**/.htaccess',
    ],
    description: 'This PR changes SSL/TLS/certificate configuration. Incorrect settings can disable encryption or create vulnerabilities.',
    recommendation: 'Review with your security team. Verify certificate chains and TLS versions. Test in staging before production.',
    emoji: '🔒',
  },
  {
    id: 'SQL_INJECTION_RISK',
    category: 'security',
    severity: 'high',
    name: 'Potential SQL Injection Risk',
    contentPatterns: [
      { pattern: /`.*\$\{.*\}.*`/i, flags: '' },  // template literals with interpolation in SQL
      { pattern: /execute\s*\(\s*['"].*\+.*['"]\s*\)/i, flags: '' }, // raw SQL with concatenation
      { pattern: /query\s*\(\s*['"].*\.format\(.*\)/i, flags: '' },
      { pattern: /"\s*\+\s*req\.(body|params|query)/i, flags: '' }, // direct user input in query
    ],
    description: 'This PR may introduce SQL injection vulnerabilities by concatenating user input into queries.',
    recommendation: 'Use parameterized queries or an ORM. Never concatenate user input directly into SQL strings.',
    emoji: '💉',
  },
  {
    id: 'AUTH_BYPASS',
    category: 'security',
    severity: 'critical',
    name: 'Authentication/Authorization Bypass Risk',
    contentPatterns: [
      { pattern: /skip.*auth/i, flags: '' },
      { pattern: /bypass.*auth/i, flags: '' },
      { pattern: /middleware.*return.*next\(\)/i, flags: '' }, // middleware not returning
      { pattern: /isAuthenticated\s*=\s*false/i, flags: '' },
      { pattern: /@.*public\s*/i, flags: '' }, // Java annotations making endpoints public
    ],
    description: 'This PR may introduce authentication bypass patterns. Critical security surfaces.',
    recommendation: 'Ensure all new endpoints have proper auth checks. Review with your security team before merge.',
    emoji: '🚨',
  },
  {
    id: 'CORS_WILDCARD',
    category: 'security',
    severity: 'high',
    name: 'Insecure CORS Configuration',
    contentPatterns: [
      { pattern: /origin\s*:\s*['"*]/i, flags: '' }, // wildcard origin
      { pattern: /Access-Control-Allow-Origin\s*:\s*\*['"]/i, flags: '' },
      { pattern: /allowedOrigins\s*:\s*\[\s*['"\*]+\s*\]/i, flags: '' },
    ],
    description: 'This PR sets CORS to allow all origins (*). This can expose APIs to cross-site attacks.',
    recommendation: 'Use specific allowed origins instead of wildcards. Prefer locking down to known frontend domains.',
    emoji: '🌐',
  },

  // ── Infrastructure & Config ──────────────────────────────────────────────
  {
    id: 'INFRA_ENV_VAR_ADD',
    category: 'infrastructure',
    severity: 'high',
    name: 'New Environment Variable Introduced',
    filePatterns: [
      '.env*',
      '**/config/**/*.ts',
      '**/config/**/*.js',
      '**/settings/**/*.py',
      '**/application*.yml',
      '**/application*.yaml',
      '**/application*.properties',
      '**/docker-compose*.yml',
      '**/.env*',
      '**/config.yaml',
      '**/config.yml',
    ],
    contentPatterns: [
      { pattern: /^\s*[A-Z_][A-Z0-9_]*\s*=/m, flags: '' },
    ],
    description: 'This PR introduces a new environment variable. New env vars need to be configured in all environments.',
    recommendation: 'Document the new variable. Ensure CI/CD pipelines are updated. Add to your environment variable registry.',
    emoji: '⚙️',
  },
  {
    id: 'INFRA_CICD_CHANGE',
    category: 'infrastructure',
    severity: 'medium',
    name: 'CI/CD Pipeline Configuration Changed',
    filePatterns: [
      '.github/workflows/*.yml',
      '.github/workflows/*.yaml',
      '**/.gitlab-ci.yml',
      '**/Jenkinsfile*',
      '**/.circleci/**',
      '**/.github/actions/**',
      '**/tekton/**/*.yaml',
      '**/.github/deployments/**',
    ],
    description: 'This PR modifies CI/CD configuration. Changes can affect build, test, and deployment pipelines.',
    recommendation: 'Review the CI/CD changes carefully. Ensure the pipeline still passes all required gates in staging.',
    emoji: '🔧',
  },
  {
    id: 'INFRA_K8S_CHANGE',
    category: 'infrastructure',
    severity: 'high',
    name: 'Kubernetes/Infrastructure Configuration Changed',
    filePatterns: [
      '**/k8s/**',
      '**/kubernetes/**',
      '**/*.kubeconfig',
      '**/helm/**',
      '**/Chart.yaml',
      '**/values.yaml',
      '**/templates/*.yaml',
      '**/docker-compose*.yml',
      '**/Dockerfile*',
      '**/.dockerignore',
    ],
    description: 'This PR changes infrastructure-as-code. Kubernetes or container changes can affect deployments.',
    recommendation: 'Review with your DevOps/SRE team. Ensure resource limits are set. Test in a staging cluster first.',
    emoji: '☸️',
  },
  {
    id: 'INFRA_TERRAFORM_CHANGE',
    category: 'infrastructure',
    severity: 'high',
    name: 'Terraform/Infrastructure-as-Code Changed',
    filePatterns: [
      '**/*.tf',
      '**/terraform/**',
      '**/.terraform/**',
      '**/ Pulumi.yaml',
    ],
    description: 'This PR modifies Terraform or IaC. Infrastructure changes can have production-wide impact.',
    recommendation: 'Run terraform plan and have it reviewed. Ensure state locking is working. Apply through the proper promotion pipeline.',
    emoji: '🏗️',
  },

  // ── Dependencies ────────────────────────────────────────────────────────
  {
    id: 'DEPS_NEW_OUTER',
    category: 'dependencies',
    severity: 'medium',
    name: 'New Outgoing Dependencies Added',
    filePatterns: [
      '**/package.json',
      '**/requirements.txt',
      '**/Gemfile',
      '**/go.mod',
      '**/Cargo.toml',
      '**/pom.xml',
      '**/build.gradle*',
      '**/composer.json',
      '**/pyproject.toml',
      '**/Pipfile',
      '**/poetry.lock',
      '**/yarn.lock',
      '**/pnpm-lock.yaml',
    ],
    contentPatterns: [
      { pattern: /^\+\s*"[^"]+":\s*"\^?\d/, flags: 'm' },  // new dependency entries
    ],
    description: 'This PR adds new external dependencies. New packages increase your attack surface and maintenance burden.',
    recommendation: 'Verify the package is maintained, has no known vulnerabilities, and is necessary. Check weekly downloads and issue activity.',
    emoji: '📦',
  },
  {
    id: 'DEPS_VERSION_CHANGE',
    category: 'dependencies',
    severity: 'medium',
    name: 'Dependency Version Updated',
    filePatterns: [
      'package-lock.json',
      'yarn.lock',
      'pnpm-lock.yaml',
      'requirements.lock',
      'Gemfile.lock',
      'go.sum',
      'Cargo.lock',
      'poetry.lock',
      'composer.lock',
      'package.json',
    ],
    description: 'This PR updates locked dependency versions. Major version bumps may introduce breaking changes.',
    recommendation: 'Review the changelog for breaking changes. Run integration tests. Consider pinning exact versions for security-critical deps.',
    emoji: '🔄',
  },

  // ── Test Coverage ───────────────────────────────────────────────────────
  {
    id: 'TEST_MISSING',
    category: 'testing',
    severity: 'medium',
    name: 'Code Changed Without Corresponding Tests',
    filePatterns: [
      '**/src/**',
      '**/lib/**',
      '**/app/**',
      '**/internal/**',
      '**/source/**',
    ],
    description: 'This PR modifies source code but may not include tests. New code should have test coverage.',
    recommendation: 'Add unit/integration tests for changed functionality. Aim for meaningful test coverage, not just line coverage.',
    emoji: '🧪',
  },
  {
    id: 'TEST_INTEGRATION_ADD',
    category: 'testing',
    severity: 'low',
    name: 'New Integration Tests Added',
    filePatterns: [
      '**/*integration*test*',
      '**/*e2e*test*',
      '**/*e2e*spec*',
      '**/*.test.ts',
      '**/*.test.js',
      '**/*_test.py',
      '**/*_spec.rb',
      '**/*.spec.ts',
      '**/*.spec.js',
      '**/tests/**/*.ts',
      '**/tests/**/*.js',
      '**/__tests__/**',
      '**/test/**/*.ts',
    ],
    description: 'This PR adds integration or E2E tests. Great for confidence in system behavior!',
    recommendation: 'Ensure tests run in CI and cover critical user flows.',
    emoji: '✅',
  },

  // ── PR Quality ──────────────────────────────────────────────────────────
  {
    id: 'PR_SIZE_LARGE',
    category: 'quality',
    severity: 'medium',
    name: 'Large PR — Consider Splitting',
    diffSizeThreshold: 800,
    description: 'This PR is large (>800 lines changed). Large PRs are harder to review thoroughly and more likely to contain bugs.',
    recommendation: 'Consider splitting into smaller, focused PRs. Use feature flags to merge large changes incrementally.',
    emoji: '📏',
  },
  {
    id: 'PR_SIZE_XLARGE',
    category: 'quality',
    severity: 'high',
    name: 'Very Large PR — High Review Complexity',
    diffSizeThreshold: 1500,
    description: 'This PR is very large (>1500 lines changed). Research shows PRs over 400 lines have significantly higher defect rates.',
    recommendation: 'Strongly consider splitting this PR. Each PR should ideally do one thing. Use stacked PRs if needed.',
    emoji: '🐘',
  },
  {
    id: 'PR_NO_DESCRIPTION',
    category: 'quality',
    severity: 'medium',
    name: 'PR Description Missing or Empty',
    description: 'This PR has no description. PRs without descriptions make it harder for reviewers to understand context.',
    recommendation: 'Add a clear description explaining what changed and why. Link to related issues.',
    emoji: '📝',
  },
  {
    id: 'PR_NO_BODY',
    category: 'quality',
    severity: 'low',
    name: 'PR Body Too Short',
    description: 'This PR has a very short description. Consider adding more context for reviewers.',
    recommendation: 'Include: what changed, why it changed, how to test it, screenshots for UI changes.',
    emoji: '📄',
  },
];

module.exports = { RISK_RULES };
